export const ADD_ADDRESS = "ADD_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS";
export const SET_CURRENT_ADDRESS = "SET_CURRENT_ADDRESS";
